new connection method
testng new connection method since I had a new error pop up

sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139663675586240 and this is thread id 139663639213760.